In [10]:
import pandas as pd
import numpy as np

url = 'https://www.sharkattackfile.net/spreadsheets/GSAF5.xls'
Shark_Attacks_df = pd.read_excel(url)

Realizamos un análisis inicial del datset para entender la estrucura y ver qué representa cada columna.

In [11]:
Shark_Attacks_df.shape

(7065, 23)

In [12]:
Shark_Attacks_df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,10th January,2026.0,Unprovoked,Australia,NSW,Avalon Beach,Surfing,Paul Stanton,M,?,...,Unknown,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8th January,2026.0,Unprovoked,US Virgin Islands,Fredricksted Island St Croix,Dorsch Beach,Snorkeling,Arlene Lillis,F,56,...,Unknown,Todd Smith: KevinMcMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3rd January,2026.0,Unprovoked,New Caledonia,Kélé,Between Bourail and Moindou,Scuba Diving,Unknown,M,?,...,Unknown,Andy Currie: Province Sud:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,...,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,...,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
Shark_Attacks_df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [14]:
Shark_Attacks_df.dtypes

Date               object
Year              float64
Type               object
Country            object
State              object
Location           object
Activity           object
Name               object
Sex                object
Age                object
Injury             object
Fatal Y/N          object
Time               object
Species            object
Source             object
pdf                object
href formula       object
href               object
Case Number        object
Case Number.1      object
original order    float64
Unnamed: 21        object
Unnamed: 22        object
dtype: object

In [15]:
Shark_Attacks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7065 entries, 0 to 7064
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7065 non-null   object
 1   Year            7063 non-null   float64
 2   Type            7047 non-null   object
 3   Country         7015 non-null   object
 4   State           6578 non-null   object
 5   Location        6498 non-null   object
 6   Activity        6480 non-null   object
 7   Name            6846 non-null   object
 8   Sex             6486 non-null   object
 9   Age             4070 non-null   object
 10  Injury          7030 non-null   object
 11  Fatal Y/N       6504 non-null   object
 12  Time            3538 non-null   object
 13  Species         3934 non-null   object
 14  Source          7045 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

In [16]:
Shark_Attacks_df.describe(include="all")

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
count,7065.0,7063.000000,7047,7015,6578,6498,6480,6846,6486,4070.0,...,3934,7045,6799,6794,6796,6798,6797,6799.000000,1,2
unique,6107.0,NaN,13,251,944,4611,1609,5785,10,251.0,...,1736,5399,6789,6784,6776,6777,6775,NaN,1,2
top,1957.0,NaN,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16.0,...,White shark,"K. McMurray, TrackingSharks.com",1907.10.16.R-HongKong.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2021.07.23,2012.09.02.b,NaN,stopped here,Teramo
freq,9.0,NaN,5217,2578,1192,191,1143,679,5665,92.0,...,194,131,2,2,4,2,2,NaN,1,1
mean,NaN,1935.890981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3401.152081,NaN,NaN
std,NaN,270.825801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1963.076319,NaN,NaN
min,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN
25%,NaN,1948.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1701.500000,NaN,NaN
50%,NaN,1986.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3401.000000,NaN,NaN
75%,NaN,2010.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5100.500000,NaN,NaN
max,NaN,2026.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6802.000000,NaN,NaN

Comprobamos porcentaje de nulos para decidir con qué columnas seguir.

In [17]:
Shark_Attacks_df.isna().mean().sort_values(ascending=False)

Unnamed: 21       0.999858
Unnamed: 22       0.999717
Time              0.499222
Species           0.443171
Age               0.423921
Activity          0.082803
Sex               0.081953
Location          0.080255
Fatal Y/N         0.079406
State             0.068931
href formula      0.038358
href              0.038075
Case Number.1     0.037933
Case Number       0.037792
pdf               0.037650
original order    0.037650
Name              0.030998
Country           0.007077
Injury            0.004954
Source            0.002831
Type              0.002548
Year              0.000283
Date              0.000000
dtype: float64

In [18]:
#Hemos elegido estas dos hipótesis: 
# 1. Existen tipos de injury asociados a mayor probabilidad de que el ataque sea fatal (Y/N)?
# 2. Influye el tipo de actividad en la fatalidad de los ataques de tiburón en los países con más incidentes?

Revisamos duplicados

In [19]:
Shark_Attacks_df.duplicated().sum()

np.int64(0)

Seleccionamos columnas relevantes para nuestra hipótesis.

In [20]:
Shark_Attacks_df.columns = (Shark_Attacks_df.columns.str.strip().str.lower().str.replace(" ", "_"))
Shark_Attacks_df = Shark_Attacks_df.rename(columns={"fatal_y/n": "fatal"})
Shark_Attacks_df.columns

Index(['date', 'year', 'type', 'country', 'state', 'location', 'activity',
       'name', 'sex', 'age', 'injury', 'fatal', 'time', 'species', 'source',
       'pdf', 'href_formula', 'href', 'case_number', 'case_number.1',
       'original_order', 'unnamed:_21', 'unnamed:_22'],
      dtype='object')

In [21]:
Shark_Attacks_df = Shark_Attacks_df[["country", "activity", "injury", "fatal"]]
Shark_Attacks_df.head()

,country,activity,injury,fatal
0,Australia,Surfing,puncture mark to left thumb,N
1,US Virgin Islands,Snorkeling,Left arm torn off in the attack below the elbow,Y
2,New Caledonia,Scuba Diving,Injuries to upper limbs,N
3,USA,Swimming,Taken by shark body recovered with multiple in...,Y
4,USA,Surfing,Hand Injury,N

Exploramos valores únicos

In [22]:
for col in Shark_Attacks_df:
    print(col)
    print("Valores únicos: ", Shark_Attacks_df[col].unique())
    print("Número de valores únicos: ", Shark_Attacks_df[col].nunique())

country
Valores únicos:  ['Australia' 'US Virgin Islands' 'New Caledonia' 'USA' 'French Polynesia'
 'Samoa' 'Columbia' 'Costa Rica' 'Bahamas' 'Puerto Rico' 'Spain'
 'Canary Islands' 'South Africa' 'Vanuatu' 'Jamaica' 'Israel' 'Mexico'
 'Maldives' 'Philippines' 'Turks and Caicos' 'Mozambique' 'Egypt'
 'Thailand' 'New Zealand' 'Hawaii' 'Honduras' 'Indonesia' 'Morocco'
 'Belize' 'Maldive Islands' 'Tobago' 'AUSTRALIA' 'INDIA' 'TRINIDAD'
 'BAHAMAS' 'SOUTH AFRICA' 'MEXICO' 'NEW ZEALAND' 'EGYPT' 'BELIZE'
 'PHILIPPINES' 'Coral Sea' 'SPAIN' 'PORTUGAL' 'SAMOA' 'COLOMBIA' 'ECUADOR'
 'FRENCH POLYNESIA' 'NEW CALEDONIA' 'TURKS and CaICOS' 'CUBA' 'BRAZIL'
 'SEYCHELLES' 'ARGENTINA' 'FIJI' 'MeXICO' 'ENGLAND' 'JAPAN' 'INDONESIA'
 'JAMAICA' 'MALDIVES' 'THAILAND' 'COLUMBIA' 'COSTA RICA'
 'British Overseas Territory' 'CANADA' 'JORDAN' 'ST KITTS / NEVIS'
 'ST MARTIN' 'PAPUA NEW GUINEA' 'REUNION ISLAND' 'ISRAEL' 'CHINA'
 'IRELAND' 'ITALY' 'MALAYSIA' 'LIBYA' nan 'MAURITIUS' 'SOLOMON ISLANDS'
 'ST HELENA, British overseas territory' 'COMOROS' 'REUNION'
 'UNITED KINGDOM' 'UNITED ARAB EMIRATES' 'CAPE VERDE' 'Fiji'
 'DOMINICAN REPUBLIC' 'CAYMAN ISLANDS' 'ARUBA' 'MOZAMBIQUE' 'PUERTO RICO'
 'ATLANTIC OCEAN' 'GREECE' 'ST. MARTIN' 'FRANCE' 'TRINIDAD & TOBAGO'
 'KIRIBATI' 'DIEGO GARCIA' 'TAIWAN' 'PALESTINIAN TERRITORIES' 'GUAM'
 'NIGERIA' 'TONGA' 'SCOTLAND' 'CROATIA' 'SAUDI ARABIA' 'CHILE' 'ANTIGUA'
 'KENYA' 'RUSSIA' 'TURKS & CAICOS' 'UNITED ARAB EMIRATES (UAE)' 'AZORES'
 'SOUTH KOREA' 'MALTA' 'VIETNAM' 'MADAGASCAR' 'PANAMA' 'SOMALIA' 'NEVIS'
 'BRITISH VIRGIN ISLANDS' 'NORWAY' 'SENEGAL' 'YEMEN' 'GULF OF ADEN'
 'Sierra Leone' 'ST. MAARTIN' 'GRAND CAYMAN' 'Seychelles' 'LIBERIA'
 'VANUATU' 'MEXICO ' 'HONDURAS' 'VENEZUELA' 'SRI LANKA' ' TONGA' 'URUGUAY'
 'MICRONESIA' 'CARIBBEAN SEA' 'OKINAWA' 'TANZANIA' 'MARSHALL ISLANDS'
 'EGYPT / ISRAEL' 'NORTHERN ARABIAN SEA' 'HONG KONG' 'EL SALVADOR'
 'ANGOLA' 'BERMUDA' 'MONTENEGRO' 'IRAN' 'TUNISIA' 'NAMIBIA'
 'NORTH ATLANTIC OCEAN' 'SOUTH CHINA SEA' 'BANGLADESH' 'PALAU'
 'WESTERN SAMOA' 'PACIFIC OCEAN ' 'BRITISH ISLES' 'GRENADA' 'IRAQ'
 'TURKEY' 'SINGAPORE' 'NEW BRITAIN' 'SUDAN' 'JOHNSTON ISLAND'
 'SOUTH PACIFIC OCEAN' 'NEW GUINEA' 'RED SEA' 'NORTH PACIFIC OCEAN'
 'FEDERATED STATES OF MICRONESIA' 'MID ATLANTIC OCEAN' 'ADMIRALTY ISLANDS'
 'BRITISH WEST INDIES' 'SOUTH ATLANTIC OCEAN' 'PERSIAN GULF'
 'RED SEA / INDIAN OCEAN' 'PACIFIC OCEAN' 'NORTH SEA' 'NICARAGUA '
 'MALDIVE ISLANDS' 'AMERICAN SAMOA' 'ANDAMAN / NICOBAR ISLANDAS' 'GABON'
 'MAYOTTE' 'NORTH ATLANTIC OCEAN ' 'THE BALKANS' 'SUDAN?' 'MARTINIQUE'
 'INDIAN OCEAN' 'GUATEMALA' 'NETHERLANDS ANTILLES'
 'NORTHERN MARIANA ISLANDS' 'IRAN / IRAQ' 'JAVA' 'SIERRA LEONE'
 ' PHILIPPINES' 'NICARAGUA' 'CENTRAL PACIFIC' 'SOLOMON ISLANDS / VANUATU'
 'SOUTHWEST PACIFIC OCEAN' 'BAY OF BENGAL' 'MID-PACIFC OCEAN' 'SLOVENIA'
 'CURACAO' 'ICELAND' 'ITALY / CROATIA' 'BARBADOS' 'MONACO' 'GUYANA'
 'HAITI' 'SAN DOMINGO' 'KUWAIT' 'YEMEN ' 'FALKLAND ISLANDS' 'CRETE'
 'CYPRUS' 'EGYPT ' 'WEST INDIES' 'BURMA' 'LEBANON' 'PARAGUAY'
 'BRITISH NEW GUINEA' 'CEYLON' 'OCEAN' 'GEORGIA' 'SYRIA' 'TUVALU'
 'INDIAN OCEAN?' 'GUINEA' 'ANDAMAN ISLANDS' 'EQUATORIAL GUINEA / CAMEROON'
 'COOK ISLANDS' 'TOBAGO' 'PERU' 'AFRICA' 'ALGERIA' 'Coast of AFRICA'
 'TASMAN SEA' 'GHANA' 'GREENLAND' 'MEDITERRANEAN SEA' 'SWEDEN' 'ROATAN'
 'Between PORTUGAL & INDIA' 'DJIBOUTI' 'BAHREIN' 'KOREA' 'RED SEA?'
 'ASIA?' 'CEYLON (SRI LANKA)']
Número de valores únicos:  251
activity
Valores únicos:  ['Surfing' 'Snorkeling' 'Scuba Diving' ...
 'Crew swimming alongside their anchored ship' '4 men were bathing'
 'Wreck of  large double sailing canoe']
Número de valores únicos:  1609
injury
Valores únicos:  ['puncture mark to left thumb'
 'Left arm torn off in the attack below the elbow '
 'Injuries to upper limbs' ... 'FATAL, leg stripped of flesh  '
 'FATAL, knocked overboard by tail of shark & carried off by shark '
 'FATAL. "Shark bit him in half, carrying away the lower extremities" ']
Número de valores únicos:  4179
fatal
Valores únicos:  ['N' 'Y' 'F' 'M' nan 'n' 'Nq' 'UNKNOWN' 2017 'Y x 2' ' N' 'N ' 'y']
Número de valores únicos:  12

In [23]:
for col in Shark_Attacks_df:
    Shark_Attacks_df[col] = Shark_Attacks_df[col].astype(str).str.lower().str.strip()

Shark_Attacks_df

,country,activity,injury,fatal
0,australia,surfing,puncture mark to left thumb,n
1,us virgin islands,snorkeling,left arm torn off in the attack below the elbow,y
2,new caledonia,scuba diving,injuries to upper limbs,n
3,usa,swimming,taken by shark body recovered with multiple in...,y
4,usa,surfing,hand injury,n
...,...,...,...,...
7060,australia,diving,fatal,y
7061,australia,pearl diving,fatal,y
7062,usa,swimming,fatal,y
7063,panama,nan,fatal,y
7064,ceylon (sri lanka),swimming,"fatal. ""shark bit him in half, carrying away t...",y

Nos quedamos con el primer país en ataques que han sucedido entre 2 países.

In [29]:
Shark_Attacks_df['country'] = (Shark_Attacks_df['country'].str.split('/').str[0])

In [30]:
Shark_Attacks_df['country'] = (Shark_Attacks_df['country'].str.replace(r"[\.\/\?\(\)]", "", regex=True))

In [31]:
Shark_Attacks_df['country'].value_counts().head(20)

country
usa                 2578
australia           1516
south africa         599
new zealand          146
bahamas              141
papua new guinea     136
brazil               122
mexico               107
italy                 72
fiji                  70
new caledonia         67
philippines           65
reunion               60
egypt                 53
mozambique            50
nan                   50
cuba                  49
spain                 47
india                 41
french polynesia      40
Name: count, dtype: int64

In [33]:
Shark_Attacks_df['country'].nunique()

210

In [49]:
print("Top 3 países tras la limpieza:")
top_3_paises = (Shark_Attacks_df['country'].value_counts().head(3).index.tolist())
print (top_3_paises)

Top 3 países tras la limpieza:
['usa', 'australia', 'south africa']

In [50]:
df_top3 = Shark_Attacks_df[Shark_Attacks_df['country'].isin(top_3_paises)]
df_top3

,country,activity,injury,fatal
0,australia,surfing,puncture mark to left thumb,n
3,usa,swimming,taken by shark body recovered with multiple in...,y
4,usa,surfing,hand injury,n
5,usa,freeing trapped shark,bite wounds to thigh,n
6,australia,swimming,serious leg injuries,n
...,...,...,...,...
7058,australia,fishing,fatal,y
7059,australia,swimming,fatal,y
7060,australia,diving,fatal,y
7061,australia,pearl diving,fatal,y
7062,usa,swimming,fatal,y

In [55]:
import re
df_top3['activity_group'] = df_top3['activity'].apply(
    lambda x: "surfing/boarding" if re.search(r"surf|boarding|bodyboard|paddle", x)
    else "swimming" if re.search(r"swim|bath|float|treading", x)
    else "fishing" if re.search(r"ish|spear|net", x)
    else "diving" if re.search(r"dive|snorkel|scuba", x)
    else "boating" if re.search(r"kayak|canoe|row|boat|sail", x)
    else "other")

df_top3['activity_group'].unique()

C:\Users\eliom\AppData\Local\Temp\ipykernel_10348\1833793567.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_top3['activity_group'] = df_top3['activity'].apply(

array(['surfing/boarding', 'swimming', 'other', 'fishing', 'diving',
       'boating'], dtype=object)

In [57]:
df_top3['injury'].nunique()

2951

In [63]:
sorted(df_top3['injury'].unique())

['',
 '"bad wound in the leg" - 7-ft shark caught in the bath same day',
 '"badly bitten by shark"',
 '"cut up very badly"',
 '"drowned, 2 days later his head was bitten off by a shark"',
 '"light scratch on hand/wrist area"',
 '"lost his arm"',
 '"lost leg"',
 '"lost part of a finger"',
 '"mauled"',
 '"minor cuts to left leg"',
 '"minor laceration to shoulder"',
 '"mysteriously disappeared" his body was found in an 18\', 750-lb shark caught at barber\'s point on 01-sep-1931',
 '"painfully injured" but no details',
 '"severely bitten" but survived',
 '"superficial injuries:',
 '"tooth marks" in left leg',
 '"very severe wounds"',
 '1 to 2-inch laceration behind knee',
 '1" to 2" cuts on right ankle & foot',
 '1-inch cut to leg',
 '1.5 cut to ankle',
 '1.5-inch laceration',
 '10 puncture wounds to right calf',
 '10" laceration on leg',
 '10-inch laceration to right foot',
 '12-inch laceration to right calf',
 '14 punctures on right thigh, swim trunks torn',
 '15 cm wound on inner thigh',
 '15 puncture wounds on foot',
 "15' shark seen with the man's body in its mouth, but shark involvement prior to death was not confirmed",
 '192 survived, but 750 perished. many were taken by sharks, including levine',
 '2 bite marks on right calf',
 '2 bites behind knee',
 '2 cm laceration on knee provoked incident',
 '2 inch laceration to left lower calf.',
 '2 lacerations on each side of achilles tendon',
 '2 lacerations on left hand by hooked shark, provoked incident',
 '2 lacerations on left thigh',
 '2 lacerations on leg, each 4" to 5" long',
 '2 lacerations on lower back, punctures on buttock',
 '2 lacerations on lower right leg',
 '2 lacerations to ankle',
 '2 lacerations to foot',
 '2 lacerations to the thigh',
 '2 minor lacerations in foot',
 '2 one-inch lacerations in left foot',
 '2 puncture wounds in left leg',
 '2 puncture wounds to  dorsum of left foot',
 '2 puncture wounds to leg',
 '2 punctures in lower leg',
 '2 punctures in upper arm',
 '2 punctures on forearm as captive shark collided with diver provoked incident',
 '2 semi-circular bites on aft starboard tube of boat',
 '2 sets of minor lacerations below her right knee',
 '2 small lacerations on left lower leg when he jumped off board and landed on the shark provoked incident',
 '2 small lacerations to bottom of foot',
 '2 small puncture wounds on left foot provoked incident',
 '2 toes bitten off',
 '2" laceration on left heel',
 "2' cut to dorsum of foot, 2 puncture wounds to sole",
 '2- to 3-inch cuts to posterior thigh',
 '2-inch cut on dorsum of left foot',
 '2-inch laceration on dorsum of foot, 1-inch laceration on sole.',
 '2-inch laceration to lower right leg',
 '2-inch laceration to upper left arm',
 '2-inch lacerations',
 '2-inch puncture wounds on right foot',
 '2-inch wound on dorsum of right foot, 1-inch wound on sole',
 '2/3rd of left calf removed',
 '20 cm injury to left calf',
 '20 punctures in right foot',
 '3 fingers bitten by hooked shark provoked incident',
 '3 fingers severed by metal trace as he tried to haul in a hooked shark. provoked accident',
 '3 gashes on hand & wrist',
 '3 lacerations below right knee',
 '3 lacerations on  right leg by speared fish provoked incident',
 '3 lacerations on foot',
 '3 lacerations on leg',
 '3 lacerations to foot',
 '3 lacerations to forearm',
 '3 lacerations to heel',
 '3 lacerations to left hand',
 "3 m to 3.7 m [10' to 12']  great hammerhead shark shark only made a threat display. no injury",
 '3 of the 4 passengers killed by sharks',
 '3 one-inch lacerations to sole of right foot',
 '3 puncture marks to left forearm',
 '3 puncture wounds in right wrist & hand',
 '3 puncture wounds on each side of her left  hand',
 '3 puncture wounds on left foot',
 '3 puncture wounds on right lateral ankle provoked incident',
 '3 puncture wounds to big toe of left foot, and laceration on arch of foot',
 '3 puncture wounds to posterior right ankle',
 '3 small puncture wounds to left leg',
 '3 small punctures in scalp & ripped nostril',
 '3 small punctures on arm',
 '3 tiny punctures & small lacerations on right ankle',
 '3 to 4 cm laceration on foot from hooked shark brought on board provoked incident',
 '3 toes of right foot were severed',
 '3 toes severed',
 '3 wounds on left hand',
 '3" laceration to left forearm',
 '3" laceration to left hip',
 '3" laceration to leg',
 '3" wound on thigh',
 '3-inch laceration to dorsal surface of left foot',
 '3-inch laceration to right foot',
 "3.2 m [10.5'] shark caught 9 days later contained human remains thought to be those of canham",
 '30cm (1ft) bite to lower calf',
 '4 cuts to posterior calf',
 '4 deep lacerations to thigh',
 '4 fingers of left hand were lacerated by shark he had shot in the head provoked incident',
 '4 lacerations above left ankle',
 '4 lacerations on the sole of his right foot',
 '4 or 5 lacerations on left ankle',
 '4 puncture wounds on right pinky finger',
 '4 punctures in left foot',
 '4 punctures on leg & board bitten',
 '4 scratches on left hand',
 '4 small lacerations on lower right leg',
 '4" cut on left foot',
 '4" laceration on left forearm',
 '4" laceration to left forearm',
 '4-inch laceration to arm',
 '40 people perished',
 '5 m white shark obsrved feeding on remains 6 days later',
 '5 minor puncture wounds to lower left leg',
 '5 puncture marks to hip',
 '5 puncture wounds in left calf',
 '5 puncture wounds to thigh',
 '5 punctures to hand from captive shark provoked incident',
 '5 to 6 lacerations on right foot & ankle',
 '5" gash in foot',
 "5' gash in leg",
 '5-inch gash on left leg',
 '5.5-inch laceration on calf',
 '6 lacerations to left hand',
 '6 puncture wounds to left ankle',
 '6 puncture wounds to lower leg',
 '6 puncture wounds to right calf',
 '6 to 8 puncture wounds to right hand',
 '6" cut to thigh',
 '6" gashes in foot & leg',
 '6" laceration to left foot',
 '6" laceration to left forearm',
 '6-inch gash on right foot',
 '7 lacerations to right foot',
 '7 puncture wounds in right forearm from hooked shark provoked incident',
 "7.6 m [25'] shark caught contained human remains",
 '8 shark-bitten bodies washed ashore',
 '8 to 10 puncture marks around knee',
 '8" laceration on left calf',
 '8-inch bite on calf',
 '9" laceration to right forearm',
 "9' shark in area when he disappeared, body not recovered",
 '9-inch gash in left foot',
 '`left foot bitten',
 'a "dead" shark grabbed by the tail bit his right torso provoked incident',
 "a 4.3 m [14'] shark made threat display. no injury, no attack",
 'a hoax - no shark was involved and wells\' "daughter" was his business partner eileen purchase who injured her finger on his boat',
 'a hoax, no shark involvement',
 'a large shark rammed boat, breaking prop shaft. no injury to occupants but boat sank several hours later',
 "abdomen & arm bitten. shark, holding him by the arm, leapt 4' to 5' above the surface",
 'abdomen & chest abraded',
 'abdomen & thigh bitten',
 'abdomen abraded',
 'abdomen abraded when he seized shark provoked incident',
 'abdomen abraded, thigh lacerated',
 'abdomen bitten',
 'abdomen lacerated',
 'abdomen lacerated, surfboard holed',
 'abdomen, buttock, thigh, arm & hand bitten',
 'abdomen, hip, leg & arm bitten',
 'abdominal and leg injuries',
 'aboriginal rock carving depicts man being attacked by a shark',
 'abrasion',
 'abrasion & 6 puncture wounds on chest after grabbing the shark by its tail provoked incident',
 'abrasion above knee',
 'abrasion on right foot, board bitten',
 'abrasion on shoulder recorded as provoked incident',
 'abrasion to chest',
 'abrasion to forearm',
 'abrasion to leg from netted shark provoked incident',
 'abrasion to right forearm from pectoral fin of a shark that leapt into his boat',
 'abrasion to right hand, lacerations to left forearm',
 'abrasions',
 'abrasions & 11 teethmarks on right lower leg',
 'abrasions & board bitten',
 'abrasions & bruises hip to ankle',
 'abrasions and cuts to sole of foot',
 'abrasions and lacerations to lower right leg',
 'abrasions on lower leg',
 'abrasions on right hand & deep laceration on middle finger',
 'abrasions to arm',
 'abrasions to elbow; collided with shark',
 'abrasions to left hand',
 'abrasions to left leg',
 'abrasions to leg',
 'abrasions to legs',
 'abrasions to shins',
 'abrasions to upper leg, laceration to ankle, scuba tank bitten',
 "after biting halverson, it bit scott's thigh",
 'after diver shot shark attempting to take his catch, shark bit right arm & tore wetsuit  provoked incident',
 'after shark was speared & hit on head, it bit the diver’s foot  provoked incident',
 'all 16 onboard perished, recovery efforts hampered by sharks',
 'alleged laceration to left ankle',
 'although his body was bitten by a shark/s, bruises on his neck & face suggested foul play & a shipmate taken into custody but no charges made',
 'although listed as  an uprovoked fatal attack by saf, he was killed by the explosion. the shark bites were post-mortem',
 'although listed as an uprovoked fatal attack by saf, shark bite on his ankle was post-mortem following death by drowning',
 'ankle & foot bitten',
 'ankle & foot lacerated',
 'ankle & foot lacerated, defense wounds on hand',
 'ankle & leg lacerated',
 'ankle & shin lacerated',
 'ankle bitten',
 'ankle bitten by small “gummy” shark, minor injury',
 'ankle bitten when she accidently stepped on the shark  provoked incident',
 'ankle bitten, but shark involvement unconfirmed',
 'ankle bitten, hand injured while striking shark',
 'ankle broken when 500-lb boated shark lashed him with its tail provoked incident',
 'ankle bruised',
 'ankle injured',
 'ankle injured by shark trapped in pool as it tried to get out provoked incident',
 'ankle lacerated',
 'ankle lacerated, lower left leg severely abraded',
 'ankle punctured & lacerated, hands abraded provoked incident',
 'ankle severely lacerated',
 'ankle twisted, swim fin bitten',
 'ankles injured',
 'apparently went missing while diving. helicopter searching for him spotted school of sharks attacking a "white object" 15\' below the surface',
 'arc of lacerations to bicep',
 'arc of punctures to lower right leg by hooked shark provoked incident',
 'arm & back bitten, heel lacerated',
 'arm & chest injured',
 'arm & leg injured',
 'arm amputated below shoulder',
 'arm bitten',
 'arm bitten by captive shark provoked incident',
 'arm bitten by hooked shark provoked incident',
 'arm bitten fatal',
 'arm bitten provoked incident',
 'arm bitten when he grabbed shark’s tail  provoked incident',
 'arm bitten while removing shark from fishing line provoked incident',
 'arm bitten while trying to secure shark caught by navy personnel from vessel provoked incident',
 'arm bitten, provoked incident',
 'arm grabbed provoked incident',
 'arm injured',
 'arm injured by hook, not by a shark',
 'arm lacerated',
 'arm lacerated (minor injury)',
 'arm lacerated by a shark that leapt onto boat',
 'arm lacerated by captive shark provoked incident',
 'arm lacerated by speared shark provoked incident',
 'arm lacerated from shoulder to wrist',
 'arm severed',
 'arm severed at elbow,  surgically amputated at shoulder',
 'arm severed, but survived',
 'arm severed, lacerations to thigh',
 'arm severed, surgically reattached',
 'arm severely lacerated',
 'arm severely lacerated by shark that had been hooked and shot provoked incident',
 'arm washed ashore. scratch marks on the humerus indicated it had been bitten by a shark, but cause of death could not be determined.',
 'arm, hand, buttock, leg and thigh bitten',
 'arm, shoulder & back bitten',
 'arms severed, but he survived',
 'as he pushd the shark away from his camera, his finger was cut on a tooth',
 'attempted to frighten shark by smacking water with paddle. shark bit paddle.  no injury to surf-skier provoked incident',
 'back & arm gashed but survived',
 'back bitten',
 'back of left hand gashed',
 'back of left thigh bitten',
 'back, arm & hand injured',
 'back, buttocks, left hand & left side of face bitten',
 'bathing suit torn & "imprints of the shark\'s teeth on his body"',
 'believed drowned. uhlbrecht’s foot, and the pelvis & femur of another person recovered in gut of tiger shark shark caught on 17-aug-1900',
 'believed to have drowned. partial remains washed ashore at north beach, mylestom, new south wales on 17 december. shark involvement prior to death could not be confirmed',
 'biceps & lower arm bitten',
 'big toe bitten',
 'bite near big toe',
 'bite to abdomen',
 'bite to abdomen & left leg medial thigh',
 'bite to face',
 'bite to left ankle and knee',
 'bite to left arm',
 'bite to left hand and wrist',
 'bite to left leg',
 'bite to left leg calf muscle removed',
 'bite to left thigh & calf',
 'bite to left thigh / minor injury',
 'bite to leg',
 'bite to lower back',
 'bite to lower leg',
 'bite to posterior left knee',
 'bite to right arm',
 'bite to right foot',
 'bite to right thigh',
 'bite wounds to thigh',
 'bites by 2.5 m tiger shark were post mortem',
 'bites on legs & thighs',
 'bites to arm and upper body',
 'bitten & survived',
 'bitten above & below right knee',
 'bitten behind knee & lower leg',
 'bitten below right knee by hooked shark pulled onboard skiboat provoked incident',
 'bitten below the knee',
 'bitten by harpooned shark provoked incident',
 'bitten by hooked shark provoked incident',
 'bitten by landed shark provoked incident',
 'bitten by netted shark provoked incident',
 'bitten on ankle',
 'bitten on buttock & leg',
 'bitten on calf',
 'bitten on calf by hooked shark provoked incident',
 'bitten on foot',
 'bitten on foot when he stepped on the shark  provoked incident',
 'bitten on forearm provoked incident',
 'bitten on hand & wrist',
 'bitten on hand minor injury',
 'bitten on left arm',
 'bitten on left calf & foot',
 'bitten on left calf and ankle',
 'bitten on left hand by 4-5ft shark',
 'bitten on left leg by hooked shark provoked incident',
 'bitten on left shoulder',
 'bitten on leg',
 'bitten on leg or ankle',
 'bitten on legs',
 'bitten on legs & buttock',
 'bitten on lower right leg, reported as a minor injury',
 'bitten on right leg above the ankle',
 'bitten on right thigh & calf',
 'bitten on the arm',
 'bitten on their feet by landed sharks / lacerations only provoked incidents',
 'bitten on thigh and buttocks',
 'bitten on upper right thigh & right ankle',
 'bitten twice on the leg by a shark he was attempting to free from his line provoked incident',
 'bitten underneath left arm',
 'black eye',
 'board rammed &  bitten, left thigh lacerated',
 "board rammed by shark, skegs knocked loose & 5' strip of fiberglass torn off, thigh scratched by shark’s teeth",
 'board reportedly bumped by shark. no injury',
 'board snapped in two',
 'boat bitten by gaffed shark provoked incident',
 'boat followed shark; shark holed boat',
 'bodies of 5 of the 6 men on board were bitten by by sharks. sharks may have contributed to the death of some of them.',
 'body bitten by shark/s, but death may have been due to drowning',
 'body found after a week in the water apparently bitten by shark/s',
 'body found with arm severed by shark, but shark involvement prior to death was uncomfirmed',
 'body not recovered',
 'body not recovered  / may have drowned prior to shark involvement',
 'body not recovered fatal',
 'body not recovered, shorts found indicating shark bite on left side',
 'body not recovered. 3 days later some of his equipment was found on seabed appeared damaged by a shark',
 "body recovered  from 9' shark but death due to shark bite was not confirmed",
 'body recovered next morning. injuries appeared to be inflicted post mortem',
 'body recovered, mutilated by shark/s',
 'body recovery efforts were hampered by large sharks but sharks did not cause the deaths.',
 'bones and brightly colored bangles recovered  3.35 m, 145.5-kg tiger shark’s gut',
 'both arms & leg bitten',
 'both calves lacerated',
 'both feet bitten',
 'both feet lacerated',
 'both hands & heel of left foot lacerated, right foot severed',
 'both legs and arm severed',
 'both legs bitten, 2 days later gangrene necessitated surgical amputation of left leg at mid-thigh',
 'both legs bitten, one surgically amputated',
 'both legs bitten, right leg severed at mid-calf & defense wounds on right hand',
 'both legs severely lacerated',
 'both surfers boards were bumped by sharks, moolman sustained abrasions on his arm and leg',
 'both thighs  lacerated',
 'both thighs bitten',
 'both thighs were lacerated, recovered at thursday island hospital',
 'both were bitten on feet by sharks',
 'bottom of left foot gashed',
 'bruised',
 'bruised & abraded ankle',
 'bruised in falling overboard as shark bumped boat',
 'bruised ribs & tail bone, speargun broken and wetsuit cut',
 'bruised right leg',
 'bruised shoulder chest & foot',
 'bruised, when shark struck scull & catapulted her into the water',
 'bruises & minor cuts',
 'bruises & minor injuries from reef, not the shark provoked incident',
 'bruises and abrasions to face, chin, chest, both shins & feet and cut to right hand when her surfboard was struck with force',
 'bruises to arm and hand, laceration to lower leg & minor injuries to foot',
 'bruises, abrasions and some spinal and nerve damage when collided with marine animal, possibly a shark or dolphin.',
 'bruises, laceration to head, spinal cord injury & neck broken at c5/c6',
 'bumped by shark but no injury',
 'bumped by shark, legs abraded',
 'bumped, chest bitten & badly injured',
 'bumped, then knee bitten',
 'bumping to the body',
 'buttock & leg bitten',
 'buttock bitten',
 'buttock bitten & major leg wound',
 'buttock bitten, hands lacerated',
 'buttock, both legs & arm bitten',
 'buttocks & hip bitten',
 'buttocks & leg bitten',
 'buttocks bitten',
 'buttocks injured by fin or a bump',
 'buttocks, thigh, left hand & wrist injured',
 'calf & ankle bitten',
 'calf & foot lacerated',
 'calf & shin bitten',
 'calf & shin bitten  provoked incident',
 'calf / knee injured?',
 'calf bitten',
 'calf bitten while helping angler measure the shark during fishing competition provoked incident',
 'calf bitten, leg surgically amputated',
 'calf bitten, leg surgically amputated below the knee  note: by late august, 3 more bathers had been bitten by sharks at daytona beach',
 'calf bumped but no injury',
 'calf injured',
 'calf lacerated',
 'calf lacerated & board bitten',
 'calf nipped in each case',
 'calf removed',
 'calf scratched & chunk bitten from board',
 'calf severely bitten;  leg surgically amputated',
 'calf severely lacerated',
 'calf, foot & hand bitten',
 'calves bitten',
 "captive shark bit air hose & minor lacerations on diver's cheek provoked incident",
 'captive tiger shark regurgitated his arm in the coogee aquarium',
 'cause of death may have been downing',
 'cause of death most likely drowning, remains recovered in shark',
 'cause of death undetermined. 3.6 m [11\'9"] shark seen carrying body. next day, shark was killed & antoine\'s entire body was found in its gut.',
 'cause of death was drowning & preceded shark involvement',
 'cause of death was drowning, shark bites were post mortem',
 'chest & arm bruised & scratched, 15" crescent-shaped piece removed from board',
 'chest & buttocks bitten, left leg severed at knee',
 'chest bitten by speared shark provoked incident',
 'chest lacerated',
 'chest lacerated, surfboard bitten',
 'circular bite on left thigh',
 'collision with marine animal / no injury, no attack',
 'considered a doubtful incident',
 'cracked jaw & broken tooth, shark took chunk out of surfboard',
 'cut foot, but injury caused by fishing line, not the shark',
 'cut on finger, board bitten',
 'cut to index finger of hand',
 'cut to left foot',
 'cut to right knee',
 'cut to tip of finger by a captive shark provoked incident',
 'cuts & punctures to right foot',
 'cuts on fingers, hand & wrist',
 'cuts on left foot',
 'cuts on right foot',
 'cuts on right hand, provoked incident',
 'cuts to both feet',
 'cuts to both lower legs',

In [64]:
df_top3['injury'].value_counts().head(50)

injury
fatal                             346
foot bitten                        84
no injury                          56
leg bitten                         53
survived                           52
left foot bitten                   48
right foot bitten                  39
no injury, board bitten            36
no details                         28
hand bitten                        28
lacerations to foot                24
foot lacerated                     21
lacerations to left foot           20
lacerations to right foot          19
minor injury                       19
no injury, surfboard bitten        18
ankle bitten                       18
calf bitten                        17
nan                                16
right leg bitten                   16
minor injuries                     15
right calf bitten                  14
no injury to occupants             14
thigh bitten                       14
arm bitten                         14
laceration to leg                  13
fatal, body not recovered          12
no injury, kayak bitten            12
lacerations to leg                 12
heel bitten                        11
left foot lacerated                11
leg lacerated                      11
minor injury to foot               11
leg injured                        11
left calf bitten                   10
lacerations to lower leg           10
puncture wounds to foot            10
no injury, shark bit surfboard     10
left leg bitten                     9
fatal, thigh bitten                 8
minor injury to left foot           8
no injury, ski bitten               8
laceration to left foot             8
left arm bitten                     8
right foot lacerated                8
lacerations to hand                 8
left hand bitten                    8
thigh lacerated                     8
no injury, board damaged            8
lower leg bitten                    7
Name: count, dtype: int64

In [ ]:
#Viendo cuales pueden ser los valores más repetidos, los vamos a clasificar en partes generales del cuerpo.

In [71]:
df_top3['injury_group'] = df_top3['injury'].apply(
    lambda x: "head" if re.search(r"head|face|eye|scalp|mouth|neck", x)
    else "arm" if re.search(r"arm|hand|finger|shoulder|elbow|wrist", x)
    else "leg" if re.search(r"leg|thigh|foot|toe|knee|ankle|calf", x)
    else "torso" if re.search(r"torso|chest|back|abdomen|stomach", x)
    else "other")

df_top3['injury_group'].unique()

C:\Users\eliom\AppData\Local\Temp\ipykernel_10348\2344436656.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_top3['injury_group'] = df_top3['injury'].apply(

array(['other', 'arm', 'leg', 'head', 'torso'], dtype=object)

In [76]:
df_top3['fatal'].nunique()

8

In [74]:
df_top3['fatal'].unique()

array(['n', 'y', 'f', 'nan', 'm', 'nq', 'unknown', 'y x 2'], dtype=object)

In [ ]:
(df_top3['fatal'] == '').sum()

np.int64(1)

In [ ]:
df_top3['fatal_clean'] = df_top3['fatal_clean'].replace({'f': 'y', 'nan': 'unknown'})